In [3]:
import pandas as pd

In [5]:
df = pd.read_csv(r'csvs/homeprices.csv')

In [7]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

- The new thing here is **Town** .Now the predication prices have to be different based on different areas
- There are two different types of categories **Nominal Variables** and **Ordinal Variables**
- **Nominal Variables** doot have order or number relationship beetween eachother ie gender,color,places etc categories 
- **Ordinal Variables** have some sort of numerical ordering or hieraary beetween each other. i.e Education level, (high,medium,low),(satsfied,nuetral,dissatisfied). We can Order it numerically nad use simple encoding replacing high=3,medium=2,low=1
- In **Nominal categories** we Cannot Use simple Encoding. We Use Concept of **Dummy Variables**

In [21]:
print(df.town.dtypes)

object

In [19]:
#creating dummy varibles based on the town name
dummies = pd.get_dummies(df.town)
dummies

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

In [29]:
print(dummies.dtypes)
#since the dtype of the town is bool so it is giving true/false.Convert it to int

monroe township    bool
robinsville        bool
west windsor       bool
dtype: object

In [38]:
#converting bool into integer
dummies = dummies.astype(int)
dummies

    monroe township  robinsville  west windsor
0                 1            0             0
1                 1            0             0
2                 1            0             0
3                 1            0             0
4                 1            0             0
5                 0            0             1
6                 0            0             1
7                 0            0             1
8                 0            0             1
9                 0            1             0
10                0            1             0
11                0            1             0
12                0            1             0

In [42]:
#merging dummy varibles with dataframe
merged = pd.concat([df,dummies],axis='columns')
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000                1            0             0
1   monroe township  3000  565000                1            0             0
2   monroe township  3200  610000                1            0             0
3   monroe township  3600  680000                1            0             0
4   monroe township  4000  725000                1            0             0
5      west windsor  2600  585000                0            0             1
6      west windsor  2800  615000                0            0             1
7      west windsor  3300  650000                0            0             1
8      west windsor  3600  710000                0            0             1
9       robinsville  2600  575000                0            1             0
10      robinsville  2900  600000                0            1             0
11      robinsville  3100  620000                0            1             0
12      robinsville  3600  695000                0            1             0

- Now we have to **drop town**. Since we have dummy varibles to define them.
- We have to drop one of the dummy varibles to avoid **Dummy Variable Trap**.
- When each variable can we derived from rest of the variable it is called **multi-co-linear**. Which creates **dummy variable trap**

In [46]:
#dropping town and west windsor
final = merged.drop(['town','west windsor'],axis='columns')
final

    area   price  monroe township  robinsville
0   2600  550000                1            0
1   3000  565000                1            0
2   3200  610000                1            0
3   3600  680000                1            0
4   4000  725000                1            0
5   2600  585000                0            0
6   2800  615000                0            0
7   3300  650000                0            0
8   3600  710000                0            0
9   2600  575000                0            1
10  2900  600000                0            1
11  3100  620000                0            1
12  3600  695000                0            1

- We would be using LinearRegression Model which requires **independent variable** and **dependent variable**
- model.fit(independent_vaiable,dependent_variable)
- **independent_variable** are area,monroe,robinsville
- **dependent_variable** price

In [49]:
independent_variable = final.drop('price',axis='columns')
independent_variable

    area  monroe township  robinsville
0   2600                1            0
1   3000                1            0
2   3200                1            0
3   3600                1            0
4   4000                1            0
5   2600                0            0
6   2800                0            0
7   3300                0            0
8   3600                0            0
9   2600                0            1
10  2900                0            1
11  3100                0            1
12  3600                0            1

In [51]:
dependent_variable = final.price
dependent_variable

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

### Modelling LinearRegression for Prediction

In [54]:
from sklearn import linear_model

In [58]:
model = linear_model.LinearRegression()
model.fit(independent_variable,dependent_variable)

LinearRegression()

### Now we can predict the prices according to the places
- Predict price for 2800sqft in robinsvilla
- predict price for 3400sqft in west windsor

In [61]:
#predicting forfor 2800sqft in robinsvilla
#model.predict([[area,monroe,robinsvilla]])
model.predict([[2800,0,1]])

D:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([590775.63964739])

In [63]:
#predictiong for 3400sqft in west windsor
model.predict([[3400,0,0]])

D:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.66845839])

In [67]:
#if we want to know how accurate is our model the we use model.score(x,y)
#it will calculate predicted values for all of the rows in x, and compare with actual values which is y
model.score(independent_variable,dependent_variable)
#its 95.739% acurate

0.9573929037221873

## We would do Same thing using Different Method called One Hot Encoding library

- In order to use **One Hot Encoder** we need to label encoding on town column

In [75]:
#label Encoding on town column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() #create label Encoder class object

In [81]:
# making new df for predicting
dfle = df
dfle

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [87]:
#use label Encoder to fit and transform
dfle.town = le.fit_transform(dfle.town) #it takes label column as input and returns the label array. Converts label into integer
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

 once label is encoded we need to make **x(independent variable) and y(dependent variable)** for **model.fit(x,y)**

In [106]:
independent = dfle[['town','area']].values #gives 2d array instead of dataframe
independent

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]], dtype=int64)

In [97]:
dependent = dfle.price
dependent

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

#### We know we need to Create Dummy Variables.
#### For That we use onehotencoder libarry

In [125]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder() #making an OneHotEcoder class library
# Fit and transform the 'town' column
encoded_features = ohe.fit_transform(df[['town']]).toarray()
encoded_features# it made dummy variables with respect to town columns

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]])

In [131]:
encoded_df = pd.DataFrame(encoded_features, columns=ohe.get_feature_names_out(['town']))
#This line creates a pandas DataFrame from the encoded features produced by the OneHotEncoder, with appropriate column names for each generated feature.
encoded_df

    town_0  town_1  town_2
0      1.0     0.0     0.0
1      1.0     0.0     0.0
2      1.0     0.0     0.0
3      1.0     0.0     0.0
4      1.0     0.0     0.0
5      0.0     0.0     1.0
6      0.0     0.0     1.0
7      0.0     0.0     1.0
8      0.0     0.0     1.0
9      0.0     1.0     0.0
10     0.0     1.0     0.0
11     0.0     1.0     0.0
12     0.0     1.0     0.0

In [135]:
new_df = pd.concat([encoded_df,dfle],axis='columns').drop('town',axis=1)
new_df
#it made dummy variables

    town_0  town_1  town_2  area   price
0      1.0     0.0     0.0  2600  550000
1      1.0     0.0     0.0  3000  565000
2      1.0     0.0     0.0  3200  610000
3      1.0     0.0     0.0  3600  680000
4      1.0     0.0     0.0  4000  725000
5      0.0     0.0     1.0  2600  585000
6      0.0     0.0     1.0  2800  615000
7      0.0     0.0     1.0  3300  650000
8      0.0     0.0     1.0  3600  710000
9      0.0     1.0     0.0  2600  575000
10     0.0     1.0     0.0  2900  600000
11     0.0     1.0     0.0  3100  620000
12     0.0     1.0     0.0  3600  695000

In [137]:
#dropping one varables to avoid Dummy Variable trap
new_df = new_df.drop('town_2',axis=1)
new_df

    town_0  town_1  area   price
0      1.0     0.0  2600  550000
1      1.0     0.0  3000  565000
2      1.0     0.0  3200  610000
3      1.0     0.0  3600  680000
4      1.0     0.0  4000  725000
5      0.0     0.0  2600  585000
6      0.0     0.0  2800  615000
7      0.0     0.0  3300  650000
8      0.0     0.0  3600  710000
9      0.0     1.0  2600  575000
10     0.0     1.0  2900  600000
11     0.0     1.0  3100  620000
12     0.0     1.0  3600  695000

### Creating Linear Regression Model

In [143]:
ohmodel = linear_model.LinearRegression()
ohmodel.fit(new_df[['town_0','town_1','area']],new_df.price)

LinearRegression()

In [147]:
#predictiong for 3400sqft in west windsor
ohmodel.predict([[0,0,3400]])

D:\Anaconda\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([681241.6684584])

### Conclusion
- Done same Solution using two Methods **pd.get_dummies(df.town)** and **ohe.fit_transform(df[['town']]).toarray()**
- need to drop one dummy variable to avoid dumm vaariable problem
- Types of Categorical Variables 1. Ordinal 2. Nominal